<a href="https://colab.research.google.com/github/dislaybim/BIBLIOTECA-NUMPY-PYTHON/blob/main/estudar_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

ones_array = np.ones((3, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

# Criar um array de números
dados = np.array([10, 15, 20, 25, 30])

# Calcular a média
media = np.mean(dados)

# Calcular o desvio padrão
desvio_padrao = np.std(dados)

print("Dados:", dados)
print("Média:", media)
print("Desvio Padrão:", desvio_padrao)


Dados: [10 15 20 25 30]
Média: 20.0
Desvio Padrão: 7.0710678118654755


In [ ]:
import numpy as np

numeros = []

for i in range(0, 3):
    linha = []  # Inicializa uma lista vazia para cada linha
    for c in range(0, 3):
        e = (int(input("Digite um número: ")))
        linha.append(e)  # Adiciona o número à linha atual
    numeros.append(linha)  # Adiciona a linha à lista principal

faze = np.array([numeros, [1, 3, 4, 5, 6]])
print(faze)
print(type(faze))


Digite um número: 6
Digite um número: 8
Digite um número: 8
Digite um número: 9
Digite um número: 9
Digite um número: 0
Digite um número: 7
Digite um número: 6
Digite um número: 4
[list([[6, 8, 8], [9, 9, 0], [7, 6, 4]]) list([1, 3, 4, 5, 6])]
<class 'numpy.ndarray'>


<ipython-input-2-4e362096c237>:12: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  faze = np.array([numeros, [1, 3, 4, 5, 6]])


In [ ]:
print("-=-"*10)
print("      MEGA-SENA")
print("-=-"*10)
import random

quantidade = int(input("Quantidade de jogos: "))

lista = [[0 for j in range(6)] for i in range(quantidade)]

for j in range(0, quantidade):
    for i in range(0, 6):
        lista[j][i] = random.randint(0, 60)

# Imprime a matriz completa
cont=0
for j in range(0,quantidade):
  for i in range(0,6):
    con=cont+1
    print("O jogo {}={},".format(j+1,lista[j][i]), end='')
    if cont==5:
      print("\n")
      cont=0

-=--=--=--=--=--=--=--=--=--=-
      MEGA-SENA
-=--=--=--=--=--=--=--=--=--=-
Quantidade de jogos: 3
O jogo 1=32,O jogo 1=38,O jogo 1=39,O jogo 1=47,O jogo 1=60,O jogo 1=18,O jogo 2=13,O jogo 2=31,O jogo 2=8,O jogo 2=42,O jogo 2=56,O jogo 2=9,O jogo 3=1,O jogo 3=51,O jogo 3=59,O jogo 3=14,O jogo 3=4,O jogo 3=16,

aqui vou fazer um simples programa para a gente selecionar um formato de uma matrix, e obter todos os seu valores atraves de um laço de repetição
**negrito**

In [ ]:
#primeiramente, irei importar todas as biblioteca
#após isso, teremos que criar um imput, lista vazia

import numpy as np

dicionario={}
matrix = []
quant=int(input("qual a quantidade de linhas e colunas? "))

#def matriz():
for i in range(0, quant):
  linha=[] #linha vazia para armazenar durante os laços de repetição
  for j in range(0, quant):
    numero=int(input("m1[{}][{}]: ".format(i,j)))
    linha.append(numero)
  matrix.append(linha)
dicionario = matrix
format = np.array(matrix)

print(format)
print(type(format))
print(dicionario)
print("\ncarregando!!!")

#for i in range(0, quant):
  #linha2 = []
  #for j in range(0, quant):
    #num =






qual a quantidade de linhas e colunas? 2
m1[0][0]: 2
m1[0][1]: 2
m1[1][0]: 2
m1[1][1]: 2
[[2 2]
 [2 2]]
<class 'numpy.ndarray'>
[[2, 2], [2, 2]]

carregando!!!


In [ ]:
import numpy as np

quant = int(input("Qual é a quantidade de linhas e colunas? "))

# Inicialize uma matriz vazia
matrix = []

# Use um loop para preencher a matriz
for i in range(quant):
    linha = []
    for j in range(quant):
        numero = int(input("m1[{}][{}]: ".format(i, j)))
        linha.append(numero)
    matrix.append(linha)

# Converta a matriz em um array NumPy
format = np.array(matrix)

# Armazene a matriz em um dicionário
dicionario = {'matriz': format}

# Exiba a matriz NumPy, o tipo dela e o dicionário
print("\nMatriz NumPy:")
print(format)
print(type(format))

print("\nDicionário:")
print(dicionario)


KeyboardInterrupt: ignored

In [ ]:
import numpy as np

%timeit np.arange(1,9)#criar um vetor com módolo 7 de [1-8]


917 ns ± 343 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
import numpy as np
x = [1,2,3,4,5]
y = np.array([1,2,3,4,5])

print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
l = []

for i in range(1,5):
  int = input("enter : ")
  l.append(int)

print(np.array(l))

enter : 2
enter : 3
enter : 4
enter : 5
['2' '3' '4' '5']


In [ ]:
#3) vetor nulo de tamanho 10

import numpy as np

null = np.zeros(10)

print(null)
print(type(null))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

lista = []

for i in range(0,2):
    linha = []
    for j in range(0,2):
        n = int(input())
        linha.append(n)
    lista.append(linha)

memoria = np.array(lista)

# Calcule o tamanho da memória ocupada em bytes
tamanho_memoria = memoria.nbytes

print("Tamanho da memória ocupada pela matriz: {} bytes".format(tamanho_memoria))


6
7
8
9
Tamanho da memória ocupada pela matriz: 32 bytes


In [ ]:
#4) tamanho do vetor
import numpy as np

lista = []

for i in range(0, 3):
    linha = []
    for c in range(0, 3):
        var = int(input('{}{}: '.format(i,c)))
        linha.append(var)
    lista.append(linha)

memoria = np.array(lista)#cada posição de um vertor equivale a 1 byte de memoria

# Calcule o tamanho da memória ocupada em bytes
tamanho_memoria = memoria.nbytes
print(memoria)
print(type(memoria))
print("Tamanho da memória ocupada pela matriz: {} bytes".format(tamanho_memoria))


00: 5
01: 7
02: 8
10: 9
11: 4
12: 5
20: 6
21: 7
22: 7
[[5 7 8]
 [9 4 5]
 [6 7 7]]
<class 'numpy.ndarray'>
Tamanho da memória ocupada pela matriz: 72 bytes


In [ ]:
#6)vetor de modulo 10 com todos os espaços nulos, 5 posição valor 1

import numpy as np

doido = np.zeros(10)
doido[4] = 1

print(doido)
print(type(doido))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [ ]:
#7)crie um vetor com valores variando de 10 a 49

import numpy as np
tamanho = int(input("qual o tamanho do vetor? "))

vetor = np.zeros(tamanho)
z = np.arange(10,50)
z = z[::-1]#8)reverter a ordem dos números no vetor

for i in range (0,tamanho):
  vetor[i] = np.random.randint(10,49)

print(z)
print(vetor)
print(type(vetor))
print(vetor.nbytes)

qual o tamanho do vetor? 5
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[33. 46. 35. 38. 42.]
<class 'numpy.ndarray'>
40


In [ ]:
#9) criar matrix, 3x3:

import numpy as np
matrix = []

for i in range (3):
  lista = []
  for j in range (3):
    x = np.random.randint(8)
    lista.append(x)
  matrix.append(lista)

todo = np.array(matrix)

print(todo)
print(type(todo))


[[7 5 2]
 [4 7 0]
 [4 4 2]]
<class 'numpy.ndarray'>


In [ ]:
#9) criar matrix, 3x3 [0-8]:

import numpy as np

x = np.array(np.arange(3))
y = np.array(np.arange(3,6))
z = np.array(np.arange(6,9))

matri = np.array([[x],[y],[z]])



print(matri)
#print(type(matri))

[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]


In [ ]:
#9) criar matrix, 3x3 [0-8]:

import numpy as np

z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

nz = np.nonzero([1,2,0,0,4,0])#10
print(nz)#11 indentidade matriz
Z = np.eye(3)
print(Z)
x = np.random.random((3,3,3))#12)matriz 3x3x3 aleatoria

print(x)


(array([0, 1, 4]),)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[[0.3137239  0.37612192 0.66671982]
  [0.38357624 0.12703189 0.35183961]
  [0.75243756 0.43638716 0.62924196]]

 [[0.95251688 0.75044401 0.04380736]
  [0.85981843 0.45518858 0.21830548]
  [0.050833   0.98094368 0.30021422]]

 [[0.00329129 0.3656723  0.99360462]
  [0.72855135 0.90714483 0.13380833]
  [0.56977082 0.77633793 0.87932078]]]


In [ ]:
#13)array 10x10, valores aleatores, pegar valor minimo e máximo:

import numpy as np

array = np.random.random((10,10))
print(array)
print(type(array))
x = np.max(array)
y = np.min(array)

print("valor máximo: {}\nValor minimo: {}".format(x,y))

[[0.32546734 0.33439006 0.15982726 0.49892985 0.40205849 0.974606
  0.38481557 0.5932774  0.78558535 0.69801862]
 [0.63581804 0.94631281 0.59108502 0.90251907 0.83811065 0.46157557
  0.49510806 0.84164433 0.77896051 0.78270072]
 [0.23198065 0.96705378 0.63412373 0.41393047 0.12340495 0.05203399
  0.75540169 0.43560531 0.94974733 0.0868206 ]
 [0.32001065 0.38636084 0.327209   0.85111817 0.65300374 0.73224561
  0.12379524 0.16439505 0.00177546 0.61697021]
 [0.71836079 0.75498621 0.70323065 0.07558961 0.0876378  0.25854765
  0.6253549  0.38095837 0.39681806 0.42776227]
 [0.16331135 0.60879813 0.0300134  0.25218847 0.13069122 0.25544986
  0.87485014 0.02270828 0.75467548 0.30802499]
 [0.98817784 0.25935367 0.45247866 0.25136885 0.29928018 0.11077444
  0.9992708  0.68067399 0.75606169 0.50979216]
 [0.31690964 0.62499031 0.33982221 0.49460391 0.81358257 0.55897286
  0.73281613 0.16979997 0.48520105 0.4832764 ]
 [0.50381572 0.49226812 0.07954202 0.44879948 0.38909244 0.52568529
  0.68444672 0

In [ ]:
#### 14. Crie um vetor aleatório de tamanho 30 e encontre o valor médio (★☆☆)
import numpy as np

z = np.random.random((10))
mean = np.mean(z)
print(z)
print("valor médio: {}".format(mean))

[0.16277377 0.70265774 0.83052701 0.63352219 0.51693883 0.56847246
 0.25404506 0.19847991 0.72272676 0.39072647]
valor médio: 0.49808701979276215


Aqui estão exemplos de como usar algumas das funções mencionadas da biblioteca NumPy:

1. **`np.array()`:** Criar um array NumPy a partir de uma lista de Python.

```python
import numpy as np

lista = [1, 2, 3, 4, 5]
array = np.array(lista)
print(array)
```

2. **`np.mean()`:** Calcular a média de um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
media = np.mean(array)
print("Média:", media)
```

3. **`np.max()`:** Encontrar o valor máximo em um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
maximo = np.max(array)
print("Máximo:", maximo)
```

4. **`np.min()`:** Encontrar o valor mínimo em um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
minimo = np.min(array)
print("Mínimo:", minimo)
```

Esses exemplos demonstram como criar um array NumPy com `np.array()` e realizar cálculos básicos, como média, máximo e mínimo, usando `np.mean()`, `np.max()` e `np.min()`. Lembre-se de que você pode aplicar essas funções a arrays multidimensionais e personalizá-las conforme necessário para suas necessidades.

Claro, aqui estão algumas outras funções úteis da biblioteca NumPy:

5. **`np.arange()`:** Criar um array NumPy de valores espaçados uniformemente em um intervalo especificado.

```python
import numpy as np

array = np.arange(1, 11)  # Cria um array de 1 a 10
print(array)
```

6. **`np.linspace()`:** Criar um array NumPy com valores igualmente espaçados dentro de um intervalo especificado.

```python
import numpy as np

array = np.linspace(0, 1, 5)  # Cria um array de 0 a 1 com 5 valores igualmente espaçados
print(array)
```

7. **`np.zeros()`:** Criar um array NumPy preenchido com zeros.

```python
import numpy as np

array = np.zeros(5)  # Cria um array de zeros com 5 elementos
print(array)
```

8. **`np.ones()`:** Criar um array NumPy preenchido com uns.

```python
import numpy as np

array = np.ones(5)  # Cria um array de uns com 5 elementos
print(array)
```

9. **`np.eye()`:** Criar uma matriz de identidade (matriz com uns na diagonal principal e zeros em outros lugares).

```python
import numpy as np

matriz = np.eye(3)  # Cria uma matriz de identidade 3x3
print(matriz)
```

10. **`np.reshape()`:** Alterar a forma de um array NumPy para uma nova forma especificada.

```python
import numpy as np

array = np.arange(1, 7)
novo_array = np.reshape(array, (2, 3))  # Altera a forma para uma matriz 2x3
print(novo_array)
```

11. **`np.transpose()`:** Transpor um array NumPy (trocar linhas por colunas).

```python
import numpy as np

matriz = np.array([[1, 2], [3, 4]])
matriz_transposta = np.transpose(matriz)
print(matriz_transposta)
```

12. **`np.concatenate()`:** Concatenar dois ou mais arrays ao longo de um eixo especificado.

```python
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenado = np.concatenate((array1, array2))
print(concatenado)
```

Essas são apenas algumas das muitas funções disponíveis na biblioteca NumPy. Elas são essenciais para realizar operações de manipulação de dados, álgebra linear e cálculos científicos em Python.

Claro, aqui estão mais algumas funções úteis da biblioteca NumPy:

13. **`np.sum()`:** Calcular a soma dos elementos de um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
soma = np.sum(array)
print("Soma:", soma)
```

14. **`np.prod()`:** Calcular o produto dos elementos de um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
produto = np.prod(array)
print("Produto:", produto)
```

15. **`np.std()`:** Calcular o desvio padrão dos elementos de um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
desvio_padrao = np.std(array)
print("Desvio Padrão:", desvio_padrao)
```

16. **`np.var()`:** Calcular a variância dos elementos de um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
variancia = np.var(array)
print("Variância:", variancia)
```

17. **`np.argmax()`:** Encontrar o índice do valor máximo em um array NumPy.

```python
import numpy as np

array = np.array([10, 30, 20, 40, 50])
indice_maximo = np.argmax(array)
print("Índice do Valor Máximo:", indice_maximo)
```

18. **`np.argmin()`:** Encontrar o índice do valor mínimo em um array NumPy.

```python
import numpy as np

array = np.array([10, 30, 20, 5, 50])
indice_minimo = np.argmin(array)
print("Índice do Valor Mínimo:", indice_minimo)
```

19. **`np.unique()`:** Encontrar valores únicos em um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 2, 3, 3, 4, 5, 5])
valores_unicos = np.unique(array)
print("Valores Únicos:", valores_unicos)
```

20. **`np.where()`:** Encontrar os índices onde uma condição é verdadeira em um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
indices = np.where(array > 2)
print("Índices onde a condição é verdadeira:", indices)
```

Essas são mais algumas funções úteis da biblioteca NumPy para realizar diversas operações em arrays NumPy e dados numéricos. NumPy é uma ferramenta poderosa para computação científica e análise de dados em Python.



Claro, aqui estão mais algumas funções úteis da biblioteca NumPy que podem ser úteis para sua apostila:

21. **`np.median()`:** Calcular a mediana dos elementos de um array NumPy.

```python
import numpy as np

array = np.array([1, 3, 5, 7, 9])
mediana = np.median(array)
print("Mediana:", mediana)
```

22. **`np.percentile()`:** Calcular os percentis de um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
percentil_25 = np.percentile(array, 25)  # 25º percentil
percentil_75 = np.percentile(array, 75)  # 75º percentil
print("25º Percentil:", percentil_25)
print("75º Percentil:", percentil_75)
```

23. **`np.random.choice()`:** Amostrar aleatoriamente elementos de um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])
amostra = np.random.choice(array, size=3, replace=False)  # Amostra de 3 elementos sem reposição
print("Amostra Aleatória:", amostra)
```

24. **`np.unique()`:** Contar a contagem de valores únicos em um array NumPy.

```python
import numpy as np

array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
valores_unicos, contagens = np.unique(array, return_counts=True)
print("Valores Únicos:", valores_unicos)
print("Contagens:", contagens)
```

25. **`np.histogram()`:** Calcular um histograma de valores em um array NumPy.

```python
import numpy as np
import matplotlib.pyplot as plt

array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
hist, bins = np.histogram(array, bins=3)  # Calcula o histograma com 3 bins
print("Histograma:", hist)
print("Bins:", bins)

# Para plotar o histograma
plt.hist(array, bins=3)
plt.show()
```

26. **`np.loadtxt()` e `np.savetxt()`:** Carregar dados de um arquivo de texto em um array NumPy e salvar um array NumPy em um arquivo de texto.

```python
import numpy as np

# Carregar dados de um arquivo de texto em um array NumPy
dados = np.loadtxt("dados.txt")

# Salvar um array NumPy em um arquivo de texto
np.savetxt("dados_salvos.txt", dados)
```



Claro, aqui estão algumas funções da biblioteca NumPy que são úteis para análises algébricas e manipulação de matrizes:

27. **`np.dot()`:** Realizar o produto escalar entre duas matrizes ou o produto matricial entre duas matrizes.

```python
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
produto_escalar = np.dot(A, B)
print("Produto Escalar:")
print(produto_escalar)

produto_matricial = A @ B  # Outra forma de realizar o produto matricial
print("Produto Matricial:")
print(produto_matricial)
```

28. **`np.linalg.inv()`:** Calcular a matriz inversa de uma matriz NumPy.

```python
import numpy as np

A = np.array([[2, 1], [5, 3]])
inversa_A = np.linalg.inv(A)
print("Matriz Inversa:")
print(inversa_A)
```

29. **`np.linalg.det()`:** Calcular o determinante de uma matriz NumPy.

```python
import numpy as np

A = np.array([[2, 1], [5, 3]])
determinante_A = np.linalg.det(A)
print("Determinante:", determinante_A)
```

30. **`np.linalg.eig()`:** Calcular os autovalores e autovetores de uma matriz NumPy.

```python
import numpy as np

A = np.array([[2, 1], [1, 3]])
autovalores, autovetores = np.linalg.eig(A)
print("Autovalores:")
print(autovalores)
print("Autovetores:")
print(autovetores)
```

31. **`np.linalg.solve()`:** Resolver sistemas de equações lineares representados como matrizes NumPy.

```python
import numpy as np

A = np.array([[2, 1], [1, 3]])
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print("Solução do Sistema Linear:")
print(x)
```

Essas funções são essenciais para realizar operações algébricas, como multiplicação de matrizes, cálculo de inversa e determinante, análise de autovalores e autovetores, e resolução de sistemas de equações lineares. Elas são especialmente úteis em aplicações de álgebra linear e análise numérica.

Claro, aqui estão alguns exemplos de códigos que envolvem operações algébricas com a biblioteca NumPy:

32. **Multiplicação de Matrizes:** Este exemplo multiplica duas matrizes usando a função `np.dot()`.

```python
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
produto = np.dot(A, B)
print("Produto de Matrizes:")
print(produto)
```

33. **Cálculo de Inversa:** Este código calcula a matriz inversa de uma matriz usando `np.linalg.inv()`.

```python
import numpy as np

A = np.array([[2, 1], [5, 3]])
inversa_A = np.linalg.inv(A)
print("Matriz Inversa:")
print(inversa_A)
```

34. **Cálculo de Determinante:** Calcula o determinante de uma matriz usando `np.linalg.det()`.

```python
import numpy as np

A = np.array([[2, 1], [5, 3]])
determinante_A = np.linalg.det(A)
print("Determinante:", determinante_A)
```

35. **Cálculo de Autovalores e Autovetores:** Encontra os autovalores e autovetores de uma matriz usando `np.linalg.eig()`.

```python
import numpy as np

A = np.array([[2, 1], [1, 3]])
autovalores, autovetores = np.linalg.eig(A)
print("Autovalores:")
print(autovalores)
print("Autovetores:")
print(autovetores)
```

36. **Resolução de Sistema de Equações Lineares:** Resolve um sistema de equações lineares usando `np.linalg.solve()`.

```python
import numpy as np

A = np.array([[2, 1], [1, 3]])
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print("Solução do Sistema Linear:")
print(x)
```

37. **Decomposição de Valores Singulares (SVD):** Este código realiza a decomposição de valores singulares usando `np.linalg.svd()`.

```python
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
U, S, VT = np.linalg.svd(A)
print("Matriz U:")
print(U)
print("Valores Singulares:")
print(S)
print("Matriz VT (transposta de V):")
print(VT)
```

38. **Cálculo da Pseudo-inversa:** Calcula a pseudo-inversa de uma matriz usando `np.linalg.pinv()`.

```python
import numpy as np

A = np.array([[2, 1], [5, 3]])
pseudo_inversa_A = np.linalg.pinv(A)
print("Pseudo-inversa:")
print(pseudo_inversa_A)
```

Esses exemplos demonstram várias operações algébricas que podem ser realizadas com a biblioteca NumPy. Eles são úteis para aplicações em álgebra linear, análise numérica e processamento de dados.

Claro, aqui estão mais algumas funções úteis para expandir sua compreensão da biblioteca NumPy:

39. **Cálculo de Norma:** Calcule a norma (magnitude) de um vetor usando `np.linalg.norm()`.

```python
import numpy as np

vetor = np.array([3, 4])
norma = np.linalg.norm(vetor)
print("Norma do Vetor:", norma)
```

40. **Matriz de Covariância:** Calcule a matriz de covariância de um conjunto de dados usando `np.cov()`.

```python
import numpy as np

dados = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
covariancia = np.cov(dados)
print("Matriz de Covariância:")
print(covariancia)
```

41. **Matriz de Correlação:** Calcule a matriz de correlação de um conjunto de dados usando `np.corrcoef()`.

```python
import numpy as np

dados = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
correlacao = np.corrcoef(dados)
print("Matriz de Correlação:")
print(correlacao)
```

42. **Álgebra de Vetores:** Realize operações de álgebra de vetores, como soma e multiplicação por escalar.

```python
import numpy as np

vetor1 = np.array([1, 2, 3])
vetor2 = np.array([4, 5, 6])

soma = vetor1 + vetor2
produto_escalar = np.dot(vetor1, vetor2)
multiplicacao_escalar = 2 * vetor1

print("Soma de Vetores:", soma)
print("Produto Escalar:", produto_escalar)
print("Multiplicação por Escalar:", multiplicacao_escalar)
```

43. **Exponenciação de Matriz:** Calcule a exponenciação de uma matriz usando `np.linalg.matrix_power()`.

```python
import numpy as np

A = np.array([[1, 2], [3, 4]])
exponenciacao = np.linalg.matrix_power(A, 2)  # Elevar A à potência 2
print("Matriz Elevada à Potência 2:")
print(exponenciacao)
```

44. **Soma de Elementos por Coluna ou Linha:** Calcule a soma de elementos por coluna ou linha em uma matriz usando `np.sum()` com o argumento `axis`.

```python
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
soma_por_coluna = np.sum(matriz, axis=0)  # Soma por coluna
soma_por_linha = np.sum(matriz, axis=1)    # Soma por linha

print("Soma por Coluna:", soma_por_coluna)
print("Soma por Linha:", soma_por_linha)
```

Essas funções adicionais permitem que você realize uma ampla variedade de operações algébricas e análises de dados usando NumPy. Elas são especialmente úteis para tarefas mais avançadas em álgebra linear, estatísticas e processamento de dados.

In [ ]:
Claro, aqui estão algumas outras funções úteis da biblioteca NumPy:

5. **`np.arange()`:** Criar um array NumPy de valores espaçados uniformemente em um intervalo especificado.

```python
import numpy as np

array = np.arange(1, 11)  # Cria um array de 1 a 10
print(array)
```

6. **`np.linspace()`:** Criar um array NumPy com valores igualmente espaçados dentro de um intervalo especificado.

```python
import numpy as np

array = np.linspace(0, 1, 5)  # Cria um array de 0 a 1 com 5 valores igualmente espaçados
print(array)
```

7. **`np.zeros()`:** Criar um array NumPy preenchido com zeros.

```python
import numpy as np

array = np.zeros(5)  # Cria um array de zeros com 5 elementos
print(array)
```

8. **`np.ones()`:** Criar um array NumPy preenchido com uns.

```python
import numpy as np

array = np.ones(5)  # Cria um array de uns com 5 elementos
print(array)
```

9. **`np.eye()`:** Criar uma matriz de identidade (matriz com uns na diagonal principal e zeros em outros lugares).

```python
import numpy as np

matriz = np.eye(3)  # Cria uma matriz de identidade 3x3
print(matriz)
```

10. **`np.reshape()`:** Alterar a forma de um array NumPy para uma nova forma especificada.

```python
import numpy as np

array = np.arange(1, 7)
novo_array = np.reshape(array, (2, 3))  # Altera a forma para uma matriz 2x3
print(novo_array)
```

11. **`np.transpose()`:** Transpor um array NumPy (trocar linhas por colunas).

```python
import numpy as np

matriz = np.array([[1, 2], [3, 4]])
matriz_transposta = np.transpose(matriz)
print(matriz_transposta)
```

12. **`np.concatenate()`:** Concatenar dois ou mais arrays ao longo de um eixo especificado.

```python
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenado = np.concatenate((array1, array2))
print(concatenado)
```

Essas são apenas algumas das muitas funções disponíveis na biblioteca NumPy. Elas são essenciais para realizar operações de manipulação de dados, álgebra linear e cálculos científicos em Python.

In [ ]:
import numpy as np

array = np.arange(0,16).reshape(4,4)
print(array)
print(type(array))



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
<class 'numpy.ndarray'>
